name: Setup SSHX

on:
  workflow_dispatch:

jobs:
  run-sshx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cấp quyền thực thi
        run: |
          chmod +x bedrock_server || echo "bedrock_server không tồn tại hoặc chưa tải đúng"
          chmod +x playit-linux-amd64 || echo "playit-linux-amd64 không tồn tại hoặc chưa tải đúng"

      - name: Chạy Server + Playit
        run: |
          ./bedrock_server & ./playit-linux-amd64 --stdout & sleep 10 && lscpu

      - name: Push tự động
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${GITHUB_REPOSITORY}
          git add .
          git commit -m "✅ Tự động push" || echo "Không có gì để commit"
          git push origin HEAD:${GITHUB_REF}
